--- #YAML:1.0
name:               HeliosX-Logger-HiRes
version:            0.02_4931
abstract:           Helios::Logger subclass implementing high resolution 
author:
    - lajandy at cpan dotorg
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Helios:       2.3
    Time::HiRes:  
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
